export const courseCopy = {
  zh: {
    title: "我的课程", intro: "每个 module 一条进度，课次学习与作业提交分别记录。",
    demoDate: "示例数据 · 非学校记录", lastSync: "最近同步", waiting: "等待学校同步",
    demoTitle: "正在查看公开演示课程", demoBody: "这是虚构的课程、作业和学习笔记，可体验 AI 课件问答。登录同步后会自动显示你的真实课程；个人资料不会发布到 GitHub。",
    exit: "退出演示", expired: "学校登录已过期", partial: "部分学校数据暂时无法读取", retry: "保留已有进度；重新登录或完成下一轮同步后更新。",
    courses: "门课程", assignmentsDone: "项作业已交", unknownItems: "项待核实", search: "搜索课程", searchPlaceholder: "搜索 module 名称或编号",
    submitted: "已交", unknown: "待核实", missing: "未交", submission: "作业提交", noAssignments: "暂无可读取作业",
    learning: "课次学习", learned: "已学 · 自己记录", materials: "课次与资料", notes: "打开课程笔记", ask: "问课程 AI",
    noLessons: "学校接口暂未提供课次资料。", resources: "补充资料", archived: "已归档", schoolFile: "学校资料", schoolAssignments: "学校作业",
    readable: "份资料可供 AI 阅读", unreadable: "份尚未提取正文", demoLesson: "演示课次不记录个人学习进度",
    notFound: "没有找到这门课程", empty: "课程将在学校同步后出现", searchTip: "试试 module 编号，或清空搜索。", loginTip: "运行启动器并完成学校登录，即可读取课程、作业和课次资料。",
    showDemo: "查看演示课程", footer: "作业进度依据学校提交状态。勾选课次只记录学习进度，不会提交学校作业。AI 读取已提取的正文；扫描件需 OCR，过长资料可能截断。",
    total: "合计", noData: "暂无数据", overview: "课程总览", railIntro: "按 module 查看作业提交和课次学习进度。", railDetail: "展开课程，可查看资料并记录已学课次。", reminders: "查看学习提醒",
    activeCourse: "当前课程", clearCourse: "取消课程范围", courseQuestion: "请根据这门课的资料解释核心概念，并标注来源。", missingCourse: "当前没有可读取的学校正文；演示课程可体验问答。",
  },
  en: {
    title: "My courses", intro: "One progress row per module. Learning and school submissions are tracked separately.",
    demoDate: "Demo data · fictional", lastSync: "Last synced", waiting: "Waiting for school sync",
    demoTitle: "Public demo courses", demoBody: "These fictional courses, assignments and study notes let you try AI questions. Your real courses replace them after sign-in and sync. Personal data is never published to GitHub.",
    exit: "Exit demo", expired: "School sign-in expired", partial: "Some school data is unavailable", retry: "Existing progress is preserved. Sign in again or wait for the next sync.",
    courses: "courses", assignmentsDone: "assignments submitted", unknownItems: "need verification", search: "Search courses", searchPlaceholder: "Search module name or code",
    submitted: "Submitted", unknown: "Unverified", missing: "Not submitted", submission: "School submissions", noAssignments: "No readable assignments",
    learning: "Lesson learning", learned: "learned · self-reported", materials: "Lessons & materials", notes: "Open course notes", ask: "Ask course AI",
    noLessons: "The school API has not provided lesson materials.", resources: "Resources", archived: "Archived", schoolFile: "School material", schoolAssignments: "School assignments",
    readable: "materials readable by AI", unreadable: "without extracted text", demoLesson: "Demo lessons do not save personal learning progress",
    notFound: "No matching course", empty: "Courses appear after school sync", searchTip: "Try a module code or clear your search.", loginTip: "Run the launcher and sign in to load courses, assignments and lesson materials.",
    showDemo: "View demo courses", footer: "Submission progress comes from the school. Checking a lesson records learning only; it does not submit school work. AI reads extracted text. Scans need OCR and long materials may be truncated.",
    total: "Total", noData: "No data", overview: "Course overview", railIntro: "Track submissions and lesson learning by module.", railDetail: "Expand a course to read materials and mark lessons as learned.", reminders: "View study reminders",
    activeCourse: "Current course", clearCourse: "Clear course scope", courseQuestion: "Explain the main concepts using this course's materials and cite your sources.", missingCourse: "No school text is available yet. Try a demo course to test questions.",
  },
};
